// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.bs.js";
import * as Notation from "./Notation.bs.js";

import './App.css'
;

var $$Response = {};

function App(Props) {
  React.useEffect(function () {
        var params = {
          method: "GET"
        };
        $$Promise.$$catch(fetch("http://localhost:8080", params).then(function (res) {
                    return res.json();
                  }).then(function (data) {
                  var msg = data.error;
                  var tmp;
                  if (msg == null) {
                    var token = data.token;
                    tmp = (token == null) ? ({
                          TAG: /* Error */1,
                          _0: "didn't return a token"
                        }) : ({
                          TAG: /* Ok */0,
                          _0: token
                        });
                  } else {
                    tmp = {
                      TAG: /* Error */1,
                      _0: msg
                    };
                  }
                  return Promise.resolve(tmp);
                }), (function (e) {
                var msg;
                if (e.RE_EXN_ID === $$Promise.JsError) {
                  var msg$1 = e._1.message;
                  msg = msg$1 !== undefined ? msg$1 : "";
                } else {
                  msg = "Unexpected error occurred";
                }
                return Promise.resolve({
                            TAG: /* Error */1,
                            _0: msg
                          });
              }));
      });
  return React.createElement("div", undefined, React.createElement(Notation.make, {
                  comment: "This is a great chessgame to observe!"
                }));
}

var make = App;

export {
  $$Response ,
  make ,
}
/*  Not a pure module */
