// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Notation(Props) {
  var comment = Props.comment;
  return React.createElement("div", {
              className: "annotation-container"
            }, React.createElement("p", undefined, comment));
}

var make = Notation;

export {
  make ,
}
/* react Not a pure module */
